version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: tfg_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: tfg_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
