lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # ruta a tu clave privada
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # ruta a tu clave pública
    pass_phrase: 'funkmoes'                                  # la passphrase que usaste para encriptar la clave privada
    token_ttl: 3600                                          # duración del token en segundos (1 hora)
